### ISSUE TITLE
Get wrong result

### ISSUE THREAD

**Issue by cristian-sima** [InvokIT/js-untar#10]
Hi. I use HTML5 form to upload a tar, untar it in order to get an XML file and then upload the XML file to the server.

This is the code

```js
const
  problemWithTheFile = "Something went wrong",
  [myArchieve] = files,
  reader = new FileReader();

// Closure to capture the file information.
reader.onload = (((theFile) => (event) => {
  
  untar(event.target.result).then(
    (extractedFiles) => {
      const [xmlFile] = extractedFiles;
      
      console.log("xmlFile.readAsString()", xmlFile.readAsString());
      
      
      // ... then I can use the XML file
    },
    () => {
      alert(problemWithTheFile);
    }
  );
})(myArchieve));

reader.readAsArrayBuffer(myArchieve);
```

When I look at console I see this:
![image](https://cloud.githubusercontent.com/assets/12199042/21902174/9d41fd68-d903-11e6-9a51-c27d982a69c7.png)

I can not upload the archive, but it contains a single XML file and it works when trying to use with other programs.

@Qvazar Any idea on this? I would really appreciate if you can help me.

Thanks

**Comment by megawac** [comment]
Are you openning a `tar.gz` file instead of a `tar` file?

**Comment by stefanbohacek** [comment]
Is there a way to handle `tar.gz` files as well?
