### ISSUE TITLE
Please specify a roadmap to 1.0

### ISSUE THREAD

**Issue by ajvincent** [InvokIT/js-untar#12]
I've been reading over the source code for this project, and it seems fairly simple and effective.  The fact you have Jasmine tests that pass right now in Google Chrome and Mozilla Firefox is a big plus for me:  those are the platforms I'm primarily developing for in my project, and I want to add your library to my [static Github site](https://ajvincent.github.io/es7-membrane/gui/) as a tool.

That said, I generally don't like relying on pre-1.0 packages, especially for a project that itself is near its 1.0 release.

So I'm asking you directly:  what prevents you from releasing your current code as 1.0 now?  :-)

**Comment by Qvazar** [comment]
v1.0.0 released
