### ISSUE TITLE
Issue on IE 10 / 11

### ISSUE THREAD

**Issue by arantes555** [InvokIT/js-untar#15]
I have an issue on IE 10 and 11. Indeed, the built `untar.js` file tries to load its Worker through a blob URL. However, IE refuses to load a Worker from a blob URL as it's considered as being from another origin, so it throws a SecurityError.

@Qvazar would it be possible to provide another build that does not include the worker code, but instead loads it from a given URL, so that it would be possible to use js-untar from IE 10 / 11 ? Thanks !

**Comment by Qvazar** [comment]
I found a bug report for this in IE. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/280849/
It should be fixed though. Can you reproduce the issue using the test URL in the bug report?

**Comment by arantes555** [comment]
Yes, I can always reproduce the issue on IE10. On IE11, it's more subtle, as  this example gives an Error like IE10 on local pages, but succeeds on internet pages.

However, it's not *really* a bug from IE (for once..), it's apparently more of a disagreement in interpreting the spec between them and all other browser vendors regarding whether or not Blob URIs are from the same origin (source: this page https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers has a note about this). Also, Microsoft aknowledged the issue but they won't fix anything not security-related on IE anymore : https://connect.microsoft.com/IE/feedback/details/801810/web-workers-from-blob-urls-in-ie-10-and-11 .

**Comment by arantes555** [comment]
@Qvazar Sorry to bother you again, but would such a build (with a separate file for the worker code) be possible ? I totally understand if you do not want to provide it as part of the official package.

**Comment by arantes555** [comment]
After further investigation, even splitting into different files doesn't help on null origins (local html files) trying to load script from remote servers. IE really has strange behaviour... Sorry for the bother.
