### ISSUE TITLE
extract specific file

### ISSUE THREAD

**Issue by marcstreeter** [InvokIT/js-untar#20]
I may just not know where to look for the documentation (if so please point me there),but I'm looking for a way to only extract one of the files (where I know the filename) in the tar archive. In the case where I have the following structure tar'ed

    - compressedFolder
        - README.md
        - ... (other files)
        
and all I want is the `README.md`  - how would I only extract the one file without extracting the others (I'm trying to avoid GB's of data where I only want the one text file).

**Comment by Qvazar** [comment]
The tar file format is all-or-nothing. Unfortunately there's no way to extract a specific file without looping through the entire tar archive anyway.

**Comment by marcstreeter** [comment]
thank you for responding.
