### ISSUE TITLE
Does this inflate .tar.gz archives?

### ISSUE THREAD

**Issue by stuartpb** [InvokIT/js-untar#5]
The readme says

> Useful when packing all your application images/sound/json/etc. data in a standard .tar file and serving to clients as one gzipped bundle.

but it looks like reading a gzipped bundle would require importing another library for inflation like pako.

**Comment by Qvazar** [comment]
Simply serve the .tar.gz with the correct headers for HTTP compression and
the receiving browser will inflate it automagically for you. There's no
need to do inflation in JavaScript.

For Nginx you can use
http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html to serve
pre-gzipped files.
For Node there's https://github.com/code42day/connect-gzip-static.
Others servers have similar features.

Den mandag den 22. februar 2016 skrev Stuart P. Bentley <
notifications@github.com>:

**Comment by Qvazar** [comment]
I assume the previous answer solved the issue.
