### ISSUE TITLE
Bad handling of files which size divides by 512

### ISSUE THREAD

**Issue by PrzemyslawBanasiak** [InvokIT/js-untar#7]
There is another problem I met while using your project. It occurs when size of file inside archive is n * 512. It jumps over the next header and things get messy. My way to fix it is:
`var dataEndPos = dataBeginPos + (file.size > 0 ? (((file.size - 1) / 512) + 1) * 512 : 0)`
You should probably test it against your data too.

**Comment by Qvazar** [comment]
Fixed in v0.1.4
