### ISSUE TITLE
old android compatibility

### ISSUE THREAD

**Issue by branaway** [InvokIT/js-untar#8]
Thanks for the work. It all works well, but Android with <= 5.0 does not seem to work. Possible to remove dependencies on advanced Javascript features?

**Comment by Qvazar** [comment]
Do you get any error messages? What API does Android <= 5.0 not support? Is it the Blob API?

**Comment by branaway** [comment]
I believe it was Promise that was not supported.  Also web worker might prevent some low-end machines  from working. Is it possible you branch out a low-end version that's synch flavor.

**Comment by Qvazar** [comment]
Promise support can be got from numerous implementations.
Requirement of Web Worker support will not be removed.
